### ISSUE TITLE
Can't use saved request with env snippet in url

### ISSUE THREAD

**Issue by gevorgmargaryan** [firecampapp/Firecamp#102]
Whenever I used save request which contains variable from project level env snipped in url it fails with error
`Could't read a file:// file (Error code:37)`

URL is {{host}}/graphql
host is https://domain
application version "snap v1.0.9"

![Screenshot from 2020-04-03 17-51-55](https://user-images.githubusercontent.com/12800600/78367976-f6f4a980-75d3-11ea-8be4-9b354eaec22b.png)

there is also access key stored and used in header section which works correctly.

**Comment by Nishchit14** [comment]
Thank you @gevorgmargaryan for posting here, This bug fixed and released under [v1.1.0](https://github.com/firecampapp/Firecamp/releases/tag/v1.1.0)
