### ISSUE TITLE
Tabs of requests does not work after reopening app

### ISSUE THREAD

**Issue by gevorgmargaryan** [firecampapp/Firecamp#106]
Related to https://github.com/firecampapp/Firecamp/issues/102
Whenever I close and reopen app all ENV variables are beeing cleared from existing tabs.
I have to close and reopen all requests.
![Screenshot from 2020-04-07 17-02-20](https://user-images.githubusercontent.com/12800600/78672353-93c78780-78f1-11ea-9ab3-241e510c6e78.png)

App version is "snap v1.1.0"

**Comment by Nishchit14** [comment]
@gevorgmargaryan Thanks for posting this issue, I would like to hear your steps (maybe complete action) as I am trying to reproduce it at my end.  Can you please help with that if possible?

**Comment by gevorgmargaryan** [comment]
> @gevorgmargaryan Thanks for posting this issue, I would like to hear your steps (maybe complete action) as I am trying to reproduce it at my end. Can you please help with that if possible?

Please @Nishchit14  find attached screen recording
[firecamp_host_issue.zip](https://github.com/firecampapp/Firecamp/files/4449871/firecamp_host_issue.zip)

**Comment by Nishchit14** [comment]
It would be so helpful @gevorgmargaryan, Thank you very much!!

**Comment by Nishchit14** [comment]
Thank you @gevorgmargaryan, This is fixed in [v1.2.2](https://github.com/firecampapp/Firecamp/releases/tag/v1.2.2)
