### ISSUE TITLE
SSL/TLS flow 

### ISSUE THREAD

**Issue by shreya-gr** [firecampapp/Firecamp#115]
Hey,
One more thing, in case of the invalid certificate (ssl/tls), the app should ask the user whether or not to proceed to unsecure site like google chrome does, firecamp just refuses to connect.

I have to manually go to that site and authorize google chrome to accept connections, after which firecamp starts to work

- From Shanur Rahman

**Comment by pranavwani** [comment]
It can be done by disabling `SSL validation` from request config tab

![Screenshot from 2020-05-23 08-53-47](https://user-images.githubusercontent.com/26399261/82720646-1dc98500-9cd3-11ea-9eed-19151c9b8ca6.png)

**Comment by Nishchit14** [comment]
Shipped with [v1.2.7](https://github.com/firecampapp/Firecamp/releases/tag/v1.2.7)
