### ISSUE TITLE
Error: Type Subscription must define one or more fields.

### ISSUE THREAD

**Issue by shreya-gr** [firecampapp/Firecamp#117]
Firecamp shows this error, 
![image_10famj6](https://user-images.githubusercontent.com/21064733/83718695-3763b880-a653-11ea-922b-999fbd7ebaa0.png)

**Actual** - 
 Error: Type Subscription must define one or more fields.

![image_1fzhxq6](https://user-images.githubusercontent.com/21064733/83718829-709c2880-a653-11ea-8c37-712e1880529b.png)
 

**Reason** 
When Subscription is empty

Reported by : Cảnh Kiều

**Comment by Nishchit14** [comment]
Released under [1.4.0](https://github.com/firecampapp/Firecamp/releases/tag/1.4.0)
