### ISSUE TITLE
OpenAPI Firecamp import

### ISSUE THREAD

**Issue by shreya-gr** [firecampapp/Firecamp#118]
Bug: OpenAPI Import issue with the `URL` and works fine with `RAW`
Steps to reproduce : 
1. OpenAPI link - https://api.weather.gov/openapi.json
2. import with `URL` with is not working. Showing the error as import valid form. 

But it's working fine with RAW.

**Comment by Nishchit14** [comment]
Shipped with [v1.2.7](https://github.com/firecampapp/Firecamp/releases/tag/v1.2.7)
