### ISSUE TITLE
Support for custom header on WebSocket

### ISSUE THREAD

**Issue by Rukenshia** [firecampapp/Firecamp#19]
Hello,

I wanted to try firecamp but got stuck right at the start. I am developing a service that exposes a HTTP endpoint and after checking headers (`Authorization` in my case), upgrades  the connection to a WebSocket. I couldn't find any way to do this with Firecamp right now.

**Comment by Nishchit14** [comment]
@Rukenshia Thank you for sharing your use case, Headers do not exist in WebSocket protocol, instead, you can use `Protocols` to achieve the same thing. 

But in your case, It seems like you're upgrading from https to ws. Can you please share some blog/article or GitHub repo to review this use-case? If it is possible then We'll surely implement this feature.

**Comment by Nishchit14** [comment]
Released under [v1.4.0](https://github.com/firecampapp/Firecamp/releases/tag/1.4.0)
