### ISSUE TITLE
provide more info on invalid names

### ISSUE THREAD

**Issue by SoreGums** [firecampapp/Firecamp#25]
instead of a red box / red line / pick a valid name

say why can't use `pop` or other names that aren't allowed...

**Comment by Nishchit14** [comment]
@SoreGums Thanks for raising an issue, Can you please share more details?

Is it a Socket or WS Tab? and which input you're facing this issue. A screenshot would help the best here.

**Comment by SoreGums** [comment]
actually seems there is simply a 4char min for the name.

doesn't matter what i type as long as i get to 4 chars the box turns green

**Comment by SoreGums** [comment]
![2019-09-16 17_28_40-Firecamp](https://user-images.githubusercontent.com/317/64935945-b50a4d00-d8a7-11e9-84ba-6a3fa697152c.png)

**Comment by Nishchit14** [comment]
Yes, here 4 character is the min requirement to give *request/module/project* name. Do you have any specific requirement or use-case? please share it so we can improve it :) . According to you what limit is good for name input?

**Comment by SoreGums** [comment]
Not specifically however it's unintuitive to make a red box "your input is invalid" with no reasons... Why is there even time spent on checking how long the name is? Input accepts text, accept text what needs to be checked?

**Comment by SoreGums** [comment]
More than 0 characters is a good minimum. Cause being blank or a space is hard to display.

**Comment by Nishchit14** [comment]
Thank you @SoreGums , We'll consider your suggestion in future release.
