### ISSUE TITLE
Websocket save message not work

### ISSUE THREAD

**Issue by phpmaple** [firecampapp/Firecamp#26]
When I send and save message, next time I open this tool, it not show last saved messages

**Comment by Nishchit14** [comment]
@phpmaple IF you only click on `Send & Save` then It'll save the message in right side message collection. It's not persistence and will be empty if you close it without saving WS request. 

Click on the `Save` button just after the `Connect` button to save your WebSocket request for future use.

We're still reviewing this flow, you can share your suggestions. we'll reform it with best accessibility

**Comment by phpmaple** [comment]
I Saved Websocket request, and click on Send & Save when I send message, but message are only saved in current session, I want used it next time

**Comment by Nishchit14** [comment]
you can send it by clicking on save button, Isn't it working?


![image](https://user-images.githubusercontent.com/5078921/65936923-d50b4600-e43b-11e9-8a0d-7b018a3ddf38.png)

**Comment by Nishchit14** [comment]
I am closing it due to inactivity, feel free to reopen it if you're still facing any issue.
