### ISSUE TITLE
Scroll the page

### ISSUE THREAD

**Issue by ediline2** [firecampapp/Firecamp#33]
In new versions it would be nice to see page scroll option available via keyboard (Home, End, PgUp, PgDn). Currently it's available using mouse only.

**Comment by nvma** [comment]
Many thanks for the initiative with this app, it has completely replaced Postman and GraphQL playground for me, and has really expedited my prototyping.

I can add that it would be extremely useful to see the actual scrollbar in a response window. I'm working with REST API which gives me back 50-500 entries per request and there's no way to evaluate the size of the response by looking at the scrollbar.
[https://i.imgur.com/Zd5Vru9.png](https://i.imgur.com/Zd5Vru9.png)
It could be 10 entries, or it could be a thousand, no way to tell.

Also these three icons in the top right corner are seem to be disabled and don't feature any tooltip, so I have no idea what they are supposed to do. Maybe in-UI clarification in form of a tooltip would improve experience?

Cheers!

**Comment by Nishchit14** [comment]
Thank you @nvma for your kind words.
The scrolling issue has been fixed and It'll be shipped in a next minor release (ETA <1 week).

We're also experimenting with some cool features for GraphQL, would you like to use it and share your experience with me? It would help us to build a better app for developers and really appreciate it. :)

**Comment by Nishchit14** [comment]
Shipped with [v0.7.2](https://github.com/firecampapp/Firecamp/releases/tag/0.7.2)
