### ISSUE TITLE
Send null character to terminate stomp message

### ISSUE THREAD

**Issue by markuskruse** [firecampapp/Firecamp#45]
When sending websocket messages over stomp, you want to terminate them with a null character. Since it is a bit hard to type with a keyboard, maybe a button or special keyboard combination could set that it should be appended before sending.

**Comment by Nishchit14** [comment]
Release under [1.4.0](https://github.com/firecampapp/Firecamp/releases/tag/1.4.0) You can now send an empty message

Thanks for your contribution @markuskruse, please feel free to reopen it in case of any issue you'll face in 1.4.0

**Comment by ppo-intelligentsystems** [comment]
@Nishchit14 - I havn't been able to find the feature requested by @markuskruse .....

How do I add the NULL char to the end of eg. a STOMP connect message?

**Comment by bawantha** [comment]
> How do I add the NULL char to the end of eg. a STOMP connect message?

`message_with_null = message + "\x00"`
