### ISSUE TITLE
Unable to select and copy text due to buttons

### ISSUE THREAD

**Issue by GlobalArtLimited** [firecampapp/Firecamp#47]
Unable to select text in restFul
![Screenshot_2](https://user-images.githubusercontent.com/28756181/73140200-314b4300-4087-11ea-9aaa-ce54c17f7075.png)

**Comment by Nishchit14** [comment]
released under [v1.0.1](https://github.com/firecampapp/Firecamp/tree/1.0.1)

Thank you @GlobalArtLimited for your help.
