### ISSUE TITLE
Closing a tab outside of a project with unsaved work will succeed

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#52]
1. problem

It's easy to lose unsaved work within firecamp.

2. steps to reproduce

Open a new tab (e.g. a new API request or a format converter) that is not associated with any project => make some changes (new headers, adding data, ...) => close the tab 
![image](https://user-images.githubusercontent.com/24702416/73590206-0ece8500-44e0-11ea-8a3f-632087c60260.png) 
=> you lost all your work

3. desired behaviour

When closing a tab with unsaved work, it'd be better if the user was notified (and given a choice to save it) about the fact there's something they might lose.

4. version

Snap installed firecamp v.0.9.2

**Comment by Nishchit14** [comment]
Released under [v1.4.0](https://github.com/firecampapp/Firecamp/releases/tag/1.4.0)
