### ISSUE TITLE
"Save & Close" button too close to the edge

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#53]
1. problem

A little graphical issue when the following button is alligned with the edge of the box:

![image](https://user-images.githubusercontent.com/24702416/73590313-5d305380-44e1-11ea-95d3-35d00d4f4521.png)

2. steps to reproduce

open a tab from within a saved project => make some changes => close the tab

3. desired state

There should be a little more space between the button and the edge of the box, just like e.g. with the "Close Tab" button.

4. version

Snap installed firecamp v0.9.2

**Comment by Nishchit14** [comment]
Fixed and push in the next release.
