### ISSUE TITLE
Typos and text inconsistencies

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#54]
There're a few minor typos and text inconsistencies:

1. 5th step of the introduction
It says "valueable", it should be "valuable".
![image](https://user-images.githubusercontent.com/24702416/73590583-6d95fd80-44e4-11ea-9f27-fe1bbaaf1692.png)

2. 3rd step of the data converter introduction
"Your", no reason for a capital "Y". The second point starts with a small letter, which is not consistent with other points.
![image](https://user-images.githubusercontent.com/24702416/73590613-c06fb500-44e4-11ea-8cb2-63e1b0445f7f.png)

3. 3rd step of the Socket.IO introduction
The sentence is not started with a capital letter:
![image](https://user-images.githubusercontent.com/24702416/73590682-86eb7980-44e5-11ea-9901-e48e1dba21eb.png)

4. 4th step of the Socket.IO introduction
I'd go for "...and also save it..." word order, sounds a bit more natural:
![image](https://user-images.githubusercontent.com/24702416/73590701-b00c0a00-44e5-11ea-824a-d895702554f9.png)

5. Some points are ended with a dot, some don't
E.g. the 2nd step in AbblyChannels:
![image](https://user-images.githubusercontent.com/24702416/73590716-e0ec3f00-44e5-11ea-96ea-8adced276d55.png)
This is on multiple places, I'd go for one or the other and make it consistent throughout the app.

6. 3rd step of the AbblyChannels introduction
"Exisiting" is a typo, it should be "Existing":
![image](https://user-images.githubusercontent.com/24702416/73590726-155ffb00-44e6-11ea-9926-4ddd71e5184d.png)

7. 4th step of the Markdown introduction
What is a markdown request? "Request" should be left out in here, or sth like "Markdown Doc" should be mentioned.
![image](https://user-images.githubusercontent.com/24702416/73590752-6a9c0c80-44e6-11ea-8a47-a1070ae65830.png)

8. Left menu help when saving a new project
"description support markdown", it should either be with "supports" when description is singular, or "descriptions" should be mentioned in plural and the rest can stay the way it is.
![image](https://user-images.githubusercontent.com/24702416/73590780-bcdd2d80-44e6-11ea-8b32-32f17c582a5a.png)

Snap version of firecamp: v0.9.2.

**Comment by Nishchit14** [comment]
Thanks a lot for helping us with Grammer @pavelsaman 🙌 . Fixed and push in the next release.
