### ISSUE TITLE
Messages in WebSocket are not displayed in full

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#56]
1. problem

If I receive a long (see the example data below) message in Firecamp, the message is not displayed in full.

![image](https://user-images.githubusercontent.com/24702416/73691124-09d12780-46d2-11ea-98aa-42f3ff8c5959.png)

2. steps to reproduce

connect to a websocket server => send a long text message from the server to the firecamp client

3. example data

"cmYoDGKhnEiAJEHhetWiaEPQ3EdE9LxKR8xqj4rz5f2vQS8jzV2MjraJCz1rSy5xx7IGeQ7ZKaWcT5KVSCOyyQWmlaesklRkGPWjIouVmZO68EYAlFSPZzoD64m3KiGbWKmfZzgXnNZH1EzA6Bmanj"

4. desired behaviour

Display the whole received message by e.g. displaying the message on more lines if it is too long for one line.

5. version

Snap installed firecamp v0.9.2

**Comment by Nishchit14** [comment]
Fixed and will push in the next release cycle. Thank you @pavelsaman
