### ISSUE TITLE
Messages in WebSocket cannot be copied into clipboard

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#57]
1. problem

Sent/received messaged in WebSocket are not possible to copy into clipboard.

![image](https://user-images.githubusercontent.com/24702416/73691641-08ecc580-46d3-11ea-8369-3d1e88c23d6a.png)

If I use the right mouse button, the following menu is offered, but Copy option doesn't work:

![image](https://user-images.githubusercontent.com/24702416/73691776-4b160700-46d3-11ea-99f4-c8988f11e8dd.png)

And selecting the text by dragging the mouse over the text doesn't seem to work either.

2. steps to reproduce

send or receive a message via WebSocket => try to copy it into a clipboard

3. desired behaviour

Make the menu after the right mouse button click work, so the whole message could be coppied into a clipboard by clicking the Copy option. And make it possible to select a part of the text by dragging the mouse over it while pressing the left mouse button.

4. version

Snap installed v0.9.2

**Comment by Nishchit14** [comment]
Fixed and will push in the next release cycle.  Thank you @pavelsaman
