### ISSUE TITLE
fixed height with editing JSON in the Arguments tab

### ISSUE THREAD

**Issue by ctfrancia** [firecampapp/Firecamp#61]
When using the SocketIO feature at the very bottom sometimes the objects that I am passing through there are large/nested and so I need to drag the section up. The issue is that the height is fixed and cuts off the json, which makes editing annoying, see photo.
<img width="1331" alt="Screenshot 2020-02-07 at 11 18 23" src="https://user-images.githubusercontent.com/32075725/74021335-a4b05700-499b-11ea-81a1-1450b137f800.png">

the JSON object is 55 lines and as you can see the number 19 is cut off

**Comment by Nishchit14** [comment]
Thanks for sharing it, It seems like you're using the old version of the Firecamp. The latest version has many improvements and new designs for a better experience. and now you can save your project in your account too.

Please download the [latest version from here](https://firecamp.io/downloads/). and If you face the same issue again then please share it here with your app version.  We'll surely fix it for you :)

**Comment by ctfrancia** [comment]
that's strange as I have been updating it regularly through homebrew.

**Comment by Nishchit14** [comment]
you're right, if you're upgrading through homebrew then it should be up-to-date. So are you on `0.9.x` version or facing any issue while upgrading? I am curious to investigate this case.

**Comment by Nishchit14** [comment]
Feel free to re-open if the issue still occurs with `v1.0.0`.
