### ISSUE TITLE
HTTP method OPTION is misnamed

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#65]
1. problem

Firecamp offers a HTTP method OPTION, but such a method doesn't exist (https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods). It's a misnamed method OPTION**S**.

![image](https://user-images.githubusercontent.com/24702416/74083129-eb1bb980-4a60-11ea-88cf-5cb02288c963.png)

This causes a 405 Method Not Allowed status code, because servers can't recognise such a HTTP method.

2. steps to reproduce

go to API => choose OPTION method => make a request to a server

3. desired state

Renaming OPTION to OPTION**S** should resolve the issue.

4. version

Snap installed Firecamp v0.9.3

**Comment by Nishchit14** [comment]
I am afraid, we never tested this method :D. Thanks a lot, @pavelsaman.
