### ISSUE TITLE
Sending payload data when no body is selected

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#66]
1. problem

Firecamps sends `{}` as payload data even when No Body is selected in request section.

Request section is configured as follows:

![image](https://user-images.githubusercontent.com/24702416/74083334-14d5e000-4a63-11ea-8c8a-76dd36696ef7.png)

Yet Firecamp seems to send 2 bytes of payload data, e.g.:

```
--------------Request Headers---------------

> DELETE / HTTP/1.1
> Host: localhost:5000
> User-Agent: Firecamp/0.9.3
> Accept: */*
> Content-Length: 2
> Content-Type: application/x-www-form-urlencoded

---------------Request Data-----------------

> {}
```

![image](https://user-images.githubusercontent.com/24702416/74083352-477fd880-4a63-11ea-8080-1ee00622140c.png)

And in Wireshark:

![image](https://user-images.githubusercontent.com/24702416/74083397-eb698400-4a63-11ea-873d-63e940aeecaf.png)

I've observed this behavious with the following methods: POST, PUT, DELETE, PATCH, PURGE, LINK, UNLINK.

2. steps to reproduce

go to API => select one of the following methods: POST, PUT, DELETE, PATCH, PURGE, LINK, UNLINK => select no body in request section => make a request to the server => see Timeline section or capture the traffic using Wireshark or similar

3. desired behaviour

Send no data at all when no body is selected in the request section.

4. version

Snap installed Firecamp v0.9.3

**Comment by Nishchit14** [comment]
Fixed in `v1.0.0`, Thanks @pavelsaman for your time to test it. :)
