### ISSUE TITLE
Tab in response section in API gets switched to Body after every request

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#69]
I guess this is more of a new feature than a bug. I'll describe what I mean.

With each new API request, the tab in response section gets switched to Body. You can see the behaviour here:

![firecamp_switching_tabs](https://user-images.githubusercontent.com/24702416/74340717-b8e2c280-4da6-11ea-892e-de8f51e00f01.gif)

However, I find it a bit uncomfortable, because sometimes I want to focus on e.g. Headers, so I switch to the tab before sending a new request. But then after sending the request, I need to switch to the Headers tab again, because Firecamp automatically changed the tab to Body with each new request. All in all, it means one extra click.

I'd like it more if I stayed on whatever tab I choose no matter how many requests I send.

I observe this behaviour in version 1.0.0 for Windows OS.

**Comment by Nishchit14** [comment]
Thanks, @pavelsaman, This behaviour has been fixed and ready to ship.

**Comment by Nishchit14** [comment]
released under [v1.0.1](https://github.com/firecampapp/Firecamp/tree/1.0.1)
