### ISSUE TITLE
Firecamp doesn't pretty-print valid XML data

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#71]
1. problem

Firecamp doesn't pretty-format valid XML data after receiving such a response in API.

2. test data

endpoint `https://inveo-bambulecz-web-staging.azurewebsites.net/Feeds/Dostupnost`

3. steps to reproduce

API => request to the above-mentioned endpoint

4. current behaviour

Firecamp will display the received payload as follows:

![image](https://user-images.githubusercontent.com/24702416/74346416-dbc5a480-4daf-11ea-902a-fd72b8120dff.png)

5. desired behaviour

Pretty-print XML when such an option is chosen in the tab (Body => XML). I also tried the same endpoint in Postman and Insomnia, both pretty-printed the data:

Postman:

![image](https://user-images.githubusercontent.com/24702416/74346588-1596ab00-4db0-11ea-91a2-85bc88d42ea1.png)

Insomnia:

![image](https://user-images.githubusercontent.com/24702416/74346633-23e4c700-4db0-11ea-89e9-ee3d54abdd51.png)

I checked the validity of the data here: https://onlinexmltools.com/validate-xml

6. version

Version 1.0.0 on Windows

**Comment by Nishchit14** [comment]
Thanks, @pavelsaman, Fixed it. 

![image](https://user-images.githubusercontent.com/5078921/74528244-c8e8d680-4f4d-11ea-94b2-6a8c24b8feef.png)

**Comment by Nishchit14** [comment]
released under [v1.0.1](https://github.com/firecampapp/Firecamp/tree/1.0.1)
