### ISSUE TITLE
"Save unsaved tabs" choice is given to the user even when all tabs are saved

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#72]
1. problem

When all tabs are saved and the user clicks on close, "Save unsaved tabs" choice is given to the user.

![unsaved_markdown_tab](https://user-images.githubusercontent.com/24702416/74350424-01ee4300-4db6-11ea-8f17-3e587bb7b52f.gif)

2. steps to reproduce

open a saved Markdown document form the left menu => make some changes to the document => click on Save => close Firecamp

3. desired behaviour

When a document is already saved, don't show the "Save unsaved tabs" option when closing Firecamp.

4. version

v1.0.0 on Windows

**Comment by Nishchit14** [comment]
Thank you @pavelsaman, This is fixed in [v1.2.2](https://github.com/firecampapp/Firecamp/releases/tag/v1.2.2)
