### ISSUE TITLE
Detect CORS Problem

### ISSUE THREAD

**Issue by TerrenceChao** [firecampapp/Firecamp#75]
When you constraint the "Access-Control-Allow-Origin"(CORS Header) with the specific domain at your server-side,  it will NOT allow requests to come from other places. So there's a situation we all have been through:

Our APIs work well, but the front-end team often tell us the APIs were broken due to the following response:
"Access to XMLHttpRequest at 'application-endpoint-url' from origin 'request-url' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."
 
The testing tool we are (backend team) using CANNOT detect such this problem, hope the Firecamp can consider the situation, make the Firecamp be able to detect the CORS problem.

**Comment by Nishchit14** [comment]
Release under [1.4.0](https://github.com/firecampapp/Firecamp/releases/tag/1.4.0) You can now test CORS issue with given config as shown in below image

![image](https://user-images.githubusercontent.com/5078921/86437136-7a33b180-bd21-11ea-8f6a-ef32a915e0d2.png)


Thanks for your contribution @TerrenceChao , please feel free to reopen it in case of any issue you'll face in 1.4.0
