### ISSUE TITLE
Allow for overwriting Content-Length header field

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#77]
I guess this is more of a feature than a bug.

1. problem

Content-Length is always automatically computed by Firecamp. That's not a problem unless users want to test how their server implementations handle wrong header field sections when e.g. a wrong value of Content-Length is sent.

2. steps to reproduce

create an API req with a header field Content-Length => send the API req

3. current behaviour

Custom made Content-Length is not used in requests, it's discarded and the value that Firecamp computes is used instead:

![image](https://user-images.githubusercontent.com/24702416/74585954-ba98ca00-4fe2-11ea-803c-82d530b71dfc.png)

4. desired behaviour

Allow for overwriting any header fields. In this example, the request would look like:

```
--------------Request Headers---------------

> POST /abc HTTP/1.1
> Host: localhost:5000
> User-Agent: Firecamp/1.0.0
> Accept: */*
> content-type: application/json
> Content-Length: 180

```

5. version

snap, v1.0.0

**Comment by Nishchit14** [comment]
released under [v1.0.1](https://github.com/firecampapp/Firecamp/tree/1.0.1)

@pavelsaman feel free to reopen it if the issue still exits :)

Users can choose to set it via config in the request.
![image](https://user-images.githubusercontent.com/5078921/75544066-36662e00-5a49-11ea-984b-09265fd71d50.png)
