### ISSUE TITLE
Allow for choosing HTTP version

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#78]
Currently in version 1.0.0, there's no way a user can choose a HTTP version, Firecamp always sends http2 version in TLS Client Hello:

![image](https://user-images.githubusercontent.com/24702416/74586698-8f19dd80-4fea-11ea-971c-32f3009a1153.png)

It'd be nice if a user could control this as well. This'd be the case when testing a server implementation where somebody might need to use a specific version of HTTP protocol. E.g. choosing HTTP/1.1 when the server supports http2 is a case that's not possible to test in Firecamp at present.

**Comment by Nishchit14** [comment]
Released under [v1.4.0](https://github.com/firecampapp/Firecamp/releases/tag/1.4.0)
