### ISSUE TITLE
OpenAPI Import

### ISSUE THREAD

**Issue by danhunsaker** [firecampapp/Firecamp#79]
I was just curious whether there was a particular reason OpenAPI/Swagger import isn't supported. Most of my APIs are already documented with OpenAPI specs, and to get the most from FireCamp, I'd want to import those, rather than reconstruct their contents via the UI.

**Comment by Nishchit14** [comment]
Thanks, @danhunsaker  for sharing the issue.

 It seems like an issue we missed. Just solved it and will release it in today's release `1.0.1` probably. 

But if you wish to import then, please try direct import by `RAW` data. just click on the link shown in the below image and paste your copied OpenAPI spec in the editor and click the Import button to import it. If it still gives an error then please let me know here. It'll be up in 12hrs mostly.

![image](https://user-images.githubusercontent.com/5078921/74702487-2e7be200-5230-11ea-8820-d3558309d84d.png)

**Comment by Nishchit14** [comment]
Thank you @danhunsaker for your contribution,

Fixed and released under [v1.0.1](https://github.com/firecampapp/Firecamp/tree/1.0.1)
