### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#81]
Sometimes I caught myself pressing Ctrl + F for search functionality in Body and Timeline... it might be useful to add this since some responses might have a long body or timeline and it's faster to search in that than copying the whole section content into another text editor and search there.

It might look similar to this (taken from Postman):

![image](https://user-images.githubusercontent.com/24702416/74720566-49e9eb80-5236-11ea-88c8-d6e6f71177d1.png)

**EDIT:** This feature can be implemented even in other parts of Firecamp, Markdown docs is another place that could benefit from having this search feature implemented. Therefore, I just updated the title a bit.

**Comment by Nishchit14** [comment]
Thanks again @pavelsaman,
I am working on the new editor design and will add this feature for sure everywhere in Firecamp.

**Comment by Nishchit14** [comment]
released under [v1.0.3](https://github.com/firecampapp/Firecamp/releases/tag/1.0.3)
