### ISSUE TITLE
Allow reordering requests and modules in projects

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#82]
1. problem/feature request

Some projects might have many requests. And the order might be significant for the user. Therefore, it'd be useful to be able to reorder requests in the left menu. At present, I don't see such a feature in Firecamp, drag&drop doesn't seem to work either:

![dragging_reqs_firecamp](https://user-images.githubusercontent.com/24702416/74731126-b91c0b80-5247-11ea-8722-d42d61b417b5.gif)

The same goes for modules:

![image](https://user-images.githubusercontent.com/24702416/74731302-00a29780-5248-11ea-88bd-70ed0cbbfc37.png)

2. steps to reproduce

Create/import a project with more than one request and try to reorder them in the left menu.

3. version

Firecamp v1.0.0 for Windows

**Comment by Nishchit14** [comment]
@pavelsaman I think the method name is a handler, you can drag request by dragging the method name  (ex `GET`) and reorder it by dropping it at any other index.

Still, I can see it's a feature discovery issue, will improve it for sure :)

**Comment by pavelsaman** [comment]
@Nishchit14 you're right! I didn't try it with methods, but it actually works.
