### ISSUE TITLE
Duplicating a request does not copy over auth type

### ISSUE THREAD

**Issue by iangregsondev** [firecampapp/Firecamp#92]
Hi,

When you duplicate a request ie..

![image](https://user-images.githubusercontent.com/2370364/76706780-6de00600-66ea-11ea-943d-b2f60cf29e7c.png)

If you go under AUTH you will see its set to none, when the source has Basic in there..

If you choose basic, it remembers the username and password - just doesnt set it as active..

cheers

**Comment by Nishchit14** [comment]
Thank you @iangregsondev, This is fixed in [v1.2.2](https://github.com/firecampapp/Firecamp/releases/tag/v1.2.2)
