### ISSUE TITLE
Request failed with status code 521 

### ISSUE THREAD

**Issue by arvi** [firecampapp/Firecamp#93]
Hello,

After downloading the FireCamp 1.0.4.dmg, I can't sign in to github, email, or google. It keeps telling me Request failed with status code 521 

Thanks.

**Comment by Nishchit14** [comment]
Thanks for sharing it @arvi , We're looking into it and keep you informed with the status.

**Comment by Nishchit14** [comment]
It was a DNS  issue, Sorry for this inconvenience. Please try now, It's working now.
