### ISSUE TITLE
Rest API Client send request with duplicate query params

### ISSUE THREAD

**Issue by pranavwani** [firecampapp/Firecamp#97]
- When sending a request with query parameters, query parameters duplicates
![Screenshot from 2020-03-27 10-55-25](https://user-images.githubusercontent.com/26399261/77724649-840a9200-7019-11ea-9da7-8b00f7cc2e63.png)
Here added `id=1` but request url shown: `?id=1?id=1`

**Comment by Nishchit14** [comment]
fixed in [v1.0.8](https://github.com/firecampapp/Firecamp/releases/tag/v1.0.8)
